### ISSUE TITLE
Handling lack of Proxies 

### ISSUE THREAD

**Issue by alshakero** [Palindrom/JSONPatcherProxy#1]
As much as I advocated migration to Proxies. I'm not very comfortable with the idea of the whole app breaking with `Uncaught ReferenceError: Proxy is not defined` error. 

So I thought maybe we can invest a couple hours in handling this. I have a couple suggestions:

1) **Log a nice error**: we handle the exception with a decent error message apologizing and suggesting a modern browser. I think this should be done anyways for people who use JSONPatcherProxy alone. I didn't implement it without asking because it means an extra `if (typeof Proxy === 'function)` for every call. And this will mean > 90% of the browsers will have to pay for this `if` while they don't need it. So I would appreciate your input.

2) **Failover to `fast-json-patch`**: since JSONPatcherProxy API architecture returns a new object, it can work for both dirty and proxy checking, it can be a good idea to embed `fast-json-patch` via a CommonJS `require` and failover to it inside JSONPatcherProxy class. This is cool and clean enough, because it's mere inclusion, not duplication. The only downside is the bundle size increasing a KB or two.

3) **The third and the option I'm leaning to**: handle the lack of Proxies inside Palindrom. When I ported PuppetJS, I noticed that moving from the dirty version to the proxy version took a very little logic change. So it can be swiftly handled inside Palindrom without messing with either codebases (`fast-json-patch` and  `JSONPatcherProxy`). And this won't increase the size of the bundle, because Palindrom needs `fast-json-patch` anyways for `apply`.

I obviously offer to implement whatever you find fit, @warpech @tomalec.

**Comment by warpech** [comment]
Is the with https://github.com/GoogleChrome/proxy-polyfill good enough for a failover?

Then perhaps the nice error (1) can be just a suggestion to load that polyfill before calling JSONPatcherProxy.

**Comment by alshakero** [comment]
@warpech it's impossible to polyfill Proxies. Speaking with JSON Patch language; the whole `add` operation will be crippled. The polyfill is simply a `setter` function. And it can't handle `defineProperty` event. There is no way to trap it unless natively.

**Comment by warpech** [comment]
> your objects' prototypes will be snapshotted at the time a proxy is created. The properties of your objects can still change - you're just unable to define new ones.

That's a quote from proxy-polyfill README.md.

I thought they resolve to dirty checking, but seems that they do not. Then I suggest we don't do anything else from saying "Proxy is not supported in your environment. Consider using `jsonpatch.observe` from Fast-Json-Patch".

**Comment by warpech** [comment]
JSONPatcherProxy should not have a failover for missing ES6 Proxy.

The code that uses JSONPatcherProxy should check if ES6 Proxy is available. Otherwise, it should fall back to https://github.com/starcounter-jack/json-patch `observe` method which uses dirty checking.

Related: https://github.com/Palindrom/Palindrom/issues/180
