### ISSUE TITLE
Note multiple instances collisions in Readme

### ISSUE THREAD

**Issue by alshakero** [Palindrom/JSONPatcherProxy#11]

**Comment by warpech** [comment]
In #12 you say that this change is not valid anymore. Should this issue be closed then?

**Comment by alshakero** [comment]
Hmmm. The PR elaborates on collisions inaccurately. But collisions still happen; I'll need to document them at one point. The issue is still relevant.

**Comment by warpech** [comment]
Got it, then moving this issue to "Nice to have"
