### ISSUE TITLE
_resetCachedProxiesPath is too slow

### ISSUE THREAD

**Issue by alshakero** [Palindrom/JSONPatcherProxy#16]
With soooo much help from @Joltrix I managed to isolate the new Palindom performance bottleneck. It's `_resetCachedProxiesPath`.

It traverses the whole tree with every change and this took us back to dirty checking price. 

Possible solutions are to find smarter ways to refresh paths. The first thing came to my mind is to only update affected parts of the tree. I'm investigating this. First thing I'll do is write a benchmark to iterate over solutions faster.

Any ideas are appreciated

@tomalec @warpech

**Comment by tomalec** [comment]
Just to not, it's not the only problem.
Removing `_resetCachedProxiesPaths` heavily increases the problem on customer's performance. But it's still ~1sec slower than with old PuppetJS.

Anyway, we should start with `_resetCachedProxiesPaths`.

**Comment by tomalec** [comment]
@alshakero  can we close this one now?

**Comment by alshakero** [comment]
Yup, fixed in https://github.com/Palindrom/JSONPatcherProxy/pull/18. Details on how is mentioned in the PR's intro.
