### ISSUE TITLE
Consider 2+ instances proxies collision 

### ISSUE THREAD

**Issue by alshakero** [Palindrom/JSONPatcherProxy#19]
Currently: 
```js
var obj = {
    one: [1, 2, 3, 4, 5],
    two: {
        raz: [6, 7, 6, 5, 4]
    }
};
var observedObj = new JSONPatcherProxy(obj).observe(true, callback);
var observedObjTwo = new JSONPatcherProxy(observedObj.two).observe(true, callback2);

delete observedObj.two.raz;
```
causes an issue. The obvious solution is to deep clone before proxification. But this is taxing and maybe it should be turned on only on demand.

**Comment by warpech** [comment]
Is this an issue with Starcounter apps? If not, then I propose to not worry about this for now ([YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)).

**Comment by alshakero** [comment]
It is not.

**Comment by warpech** [comment]
Thanks for the update! Keeping it in the Freezer then

**Comment by alshakero** [comment]
I think let's close it for a cleaner repo. Multiple observation is not something we use
