### ISSUE TITLE
Adding a function produces a patch

### ISSUE THREAD

**Issue by alshakero** [Palindrom/JSONPatcherProxy#2]
Something like this:

```js
import JSONPatcherProxy from 'jsonpatcherproxy';

var myobj = { firstName: "Albert", contactDetails: { phoneNumbers: [] } };
var jsonPatcherProxy= new JSONPatcherProxy(myobj);
var observedObject = jsonPatcherProxy.observe(true, function (e) {
    console.log(e);
});

observedObject.func = function () { };
```
Produces this:

```{ op: 'add', path: '/func', value: [Function] }```

Which will break Palindrom at one point (when it tries to serialise). 

---

According to [this](https://www.w3schools.com/js/js_json_datatypes.asp), allowed types in JSON are:

* a string
* a number
* an object (JSON object)
* an array
* a boolean
* null

I am going to check for these types before adding the new property in the setter. Any arguments/counter arguments?

@warpech @tomalec

**Comment by tomalec** [comment]
Our assumption in fast-json-patch was to make it as fast as possible for JSON  and JSON Patch.
As you noticed, function is not a valid JSON value, therefore I'd not consider it as a bug. Also, I don't want to sacrifice performance for sanity checks. However, we provide separate `validate` method which should be able to check that.

From what I can see at https://github.com/Starcounter-Jack/JSON-Patch#jsonpatchvalidate-patches-array-tree-object-optional--error-jsonpatcherror, we are not checking it currently, so it would be something new to implement.

**Comment by alshakero** [comment]
That sounds much cleaner. I will dig into validate sometime soon.

**Comment by warpech** [comment]
I think the same as Tomek on this. 

Sometimes our obsession with performance is actually hitting us in productivity. But we will never be able to sanitize everything. For example, what to do with Date? See: https://github.com/Starcounter-Jack/JSON-Patch/pull/47

**Comment by alshakero** [comment]
@warpech I researched this. And found [`is-plain-object`](https://www.npmjs.com/package/is-plain-object). But it tests in a shallow manner; `is-plain-object(new Date())` is `false`, but `is-plain-object({ date: new Date })` is true.

**Comment by warpech** [comment]
> @warpech I researched this. And found [`is-plain-object`](https://www.npmjs.com/package/is-plain-object). But it tests in a shallow manner; `is-plain-object(new Date())` is `false`, but `is-plain-object({ date: new Date() })` is true.

That still is non-obvious, because an object of such ES6 class:

```js
class Rectangle {
  constructor(height, width) {
    this.height = height;
    this.width = width;
  }
}
```

stringifies in JSON just fine. Yet, it would fail the `is-plain-object` check.

> I think adding `typeof x === 'function'` to `validate` would suffice

You mean in https://github.com/Starcounter-Jack/JSON-Patch? I agree

**Comment by alshakero** [comment]
@warpech yes, there.

**Comment by alshakero** [comment]
Closing as won't fix. Isn't affecting us at all.
