### ISSUE TITLE
JSONPatcherProxy notifies objects before they can access the new values

### ISSUE THREAD

**Issue by warpech** [Palindrom/JSONPatcherProxy#21]
## Steps to reproduce

Run this test:

```js
    it('should be called when the changes are already in place', function() {
      var obj = {
        firstName: 'Albert'
      };
      var jsonPatcherProxy = new JSONPatcherProxy(obj);
      var observedObj = jsonPatcherProxy.observe(true);

      jsonPatcherProxy.observe(true, function(_patches) {
        expect(observedObj.firstName).toReallyEqual('Joachim');
      });
      observedObj.firstName = 'Joachim';
    });
```

## Expected

The test should pass

## Actual

The test fails with the error `Expected 'Albert' to really equal 'Joachim'.`

I think that the purpose of a callback is to be called **after** some a change happened.

This is causing the following problem in Starcounter apps:

- a Polymer element `<foo-elem>` changes an property
- another Polymer `<bar-elem>` is observing this property and gets notified about the change
- when `<bar-elem>` reads the change, the value of the property is not yet updated

Specifically, I needed to apply a workaround in `starcounter-include` because of that: https://github.com/Starcounter/starcounter-include/blob/343a7a0b1169d1cdb1d66c82bcedc729eb83a3a7/starcounter-include.html#L365-L367

**Comment by alshakero** [comment]
Thank you so much for the awesome reporting. Fixed in #22 and released [0.0.9](https://github.com/Palindrom/JSONPatcherProxy/releases/tag/v0.0.9).
