### ISSUE TITLE
Investigate array.prop setting behavior

### ISSUE THREAD

**Issue by alshakero** [Palindrom/JSONPatcherProxy#23]

**Comment by warpech** [comment]
@alshakero can you elaborate what's needed here? Is it related to some other issue?

**Comment by alshakero** [comment]
Sure! This is needed because currently setting `array.prop` doesn't create a patch. It's kinda of debatable wheather this is the right thing to do. 

I think the most obvious behavior is to emit patches for array props changes except `length`. WDYT?

**Comment by warpech** [comment]
I think JSONPatcherProxy should only create patches that are serializable to JSON. JavaScript array properties are not serializable to JSON, so they should **not** be emitted as patches.

Once we decide for the behavior it is good to add a test for it.

**Comment by alshakero** [comment]
Well I agree but `palindrom-client` has a test that expects array props to be reactive. So I guess @tomalec maybe has an opinion about this.

**Comment by tomalec** [comment]
It's probably a legacy from old days when we have `dom-bind-notifier` to transition from Polymer 0.x to 1.0. And  I tried to have something that covers all the cases.

I don't have a very strong opinion. I just thought that if we technically could apply such changes why not, as for `undefined`. The fact our Starcounter server cannot digest such patch and it's not a JSON Patch compliant thing, should be a reason to throw an error from Starcounter server. 

Speaking of supporting it in your Palindrom layer, I'd say let's do it in a way that is consistent and easier with remaining implementation. If it's easier to have it and process like any other object property change, without additional `if`s , sanity checks etc. - I'd do it; if it's easier to drop support for it - I'd drop it.

Regardless of the way we choose, it should result with a clear message to the developer:
- Starcounter throws,
- PalindormJS throws
> You are trying to change array's property - this is not JSON(RFC4627) & JSON-Patch(RFC6902) compliant.

**Comment by warpech** [comment]
I strongly believe that we should only create JSON-Patches that make sense according to the JSON spec. Having a property of an array is not possible for a JSON document, so we should not generate patches that try doing that.

`json-patch-tests` considers a patch that adds a property to an array to be incorrect: https://github.com/json-patch/json-patch-tests/blob/c2fae3a8af7ace5d0ed553e3f4db98d1d4379919/tests.json#L150-L152

**Comment by warpech** [comment]
> Regardless of the way we choose, it should result with a clear message to the developer:
> - Starcounter throws,
> - PalindormJS throws

I disagree, otherwise, we will throw an error at changes of the `value` property, etc. 

I think we should do what `JSON.stringify` does - silently ignore array properties.

**Comment by alshakero** [comment]
@tomalec made good points but I agree with @warpech and I lean to it since it means simply closing this issue and moving on, this is the current behavior.

Maybe retitle this issue to "Add a test: array props should be ignored".

**Comment by tomalec** [comment]
I agree to stick to the spec.
Also, I upvote adding a test for this behavior.

However, I think we faced many times the problem of not descriptive enough/lack of warnings, errors etc.

What would app developer see if he/she uses a third party element that relies on changing the property of an object that occurred to be an array? In JS world it's pretty valid, an element is supposed to work fine, but for some reason, it doesn't. How he/she could debug it then?

**Comment by alshakero** [comment]
> How he/she could debug it then?

I can easily warn about it for almost zero perf tax. Should I?
