### ISSUE TITLE
Revert Patches

### ISSUE THREAD

**Issue by jonahbron** [Palindrom/JSONPatcherProxy#33]
Is there any interest in adding undo capability to this utility?  In my particular case, it would be super useful if I could get not only the patch that represents the change that was made, but also a patch that has the ability to revert that patch.  This would allow me to build undo/redo stacks on a whole document tree.

**Comment by jonahbron** [comment]
@alshakero I'm willing to implement this feature if you think you'd merge it in.

**Comment by alshakero** [comment]
The only requirement of this library, other than that it works, is performance. We use it in a performance-critical way. And adding features that slow it down, that don't comply with the RFC, is not part of our strategy.

**Comment by warpech** [comment]
Thank for active participation in this open source project.

This proposal would change the nature of this project from single-purpose to multi-purpose, which I think is not desired

My advice is to create a fork of it, like `ReverseJSONPatcherProxy` that will perform only the reverse patches. Then you can put *both* proxies on your objects.

Or, I think this library could accept a PR that allows you configure JSONPatcherProxy with an additional callback that will be called in `setTrap`, allowing you to extend it with custom functionality.

**Comment by jonahbron** [comment]
@warpech I've decided to go in another direction to solve this problem on my end, but I do like your idea of extending with a callback.
