### ISSUE TITLE
Nested arrays deletion issue

### ISSUE THREAD

**Issue by alshakero** [Palindrom/JSONPatcherProxy#9]
When a deeply nested array (an array that has a parent array) is proxified, its path is cached in its callback. 

For example, assume you have:
```js
var model = {
   arrayOfArrays: [['item1', 'item2', 'item3', 'item4'], ['item5', 'item6', 'item7', 'item8']]
}
```
When the model is proxified, each single array of these arrays is also proxified recursively. And during this proxification, each array caches its own path in the Proxy `set` callback. And this means `item6` of:
```js
['item5', 'item6', 'item7', 'item8']
```
has the path `/arrayOfArrays/1/1`.

Now when we delete the first array (`['item1', 'item2', 'item3', 'item4']`), second array's path is rendered incorrect.

Because it thinks its path is `/arrayOfArrays/1`. While it should change to `/arrayOfArrays/0` after first array deletion. I will investigate an efficient way to overcome this. Doesn't sound trivial.

Related to: https://github.com/StarcounterApps/CssVariablesManager/issues/25

This mention is just an FYI mention @tomalec @warpech

_(because I noticed I'm the only one watching the repo)_

**Comment by tomalec** [comment]
It seems you need to apply JSON Patches also to the cached proxies' paths.

**Comment by alshakero** [comment]
Exactly. But this isn't easy because `path` is just a local variable that lives in side `set` function of traps object. Without new proxification it's kinda hard. I'm digging.

**Comment by rogeralsing** [comment]
Lars managed to get break this in a major way today.

He has a list of details, and the list is sorted by detail name.

So imagine the following data (name and index just for the sake of the example)
```
a | 1
b | 2
c | 3
```
if you now edit the first line and change `a` to `d`. this line will now be moved to the bottom.
As expected as the list is sorted.
If he now tabs into the index field and changes the `3` to a `4`, this number will now also show up in the top index input, the one that is now dedicated to `b | 2`

The effect is that you can now edit two values in the same time.

Maybe the Path can be calculated recursively from child to parent to grandparent etc on demand?
(Not my business how it's done or fixed but hey, always fun to speculate :-) )

**Comment by alshakero** [comment]
> Maybe the Path can be calculated recursively from child to parent to grandparent etc on demand?
 
Close enough! We do this now every time the hierarchy changes and we cache paths for later usage. The [PR](https://github.com/Palindrom/JSONPatcherProxy/pull/10) is almost done and will be merged soon.

**Comment by Joltrix** [comment]
@alshakero Have this issue been solved? And if so, Do i need to update/do something specific? Cause I am still having this issue

**Comment by alshakero** [comment]
Partially. What SC version do you have?

**Comment by Joltrix** [comment]
The latest RC. version 2.3.1.6981

**Comment by alshakero** [comment]
Could you elaborate a bit? Is it exactly this issue? If yes, a GIF would be awesome. If not, could you create another issue please?

**Comment by Joltrix** [comment]
I'll try to elaborate.

First difference, it's not a nested array. It's just a normal array, where I display X buttons.

If I, at runtime, delete one of these buttons. Then the other buttons logic becomes weird.

What happens is not always the same though..
Sometimes, and most of the times, the last button "cannot be pressed" (the JSON patch never reaches the server side to trigger the handler. Even though the value is incremented in the JS.)
and other times, the buttons "point" to wrong handlers. For example, clicking button 1, would cause buttons 2 handler to trigger. Which I suspect is caused depending on which button is deleted.
If I refresh the page, all the problems disappear

![buttonstopsworking](https://user-images.githubusercontent.com/10708580/29267912-0221f24e-80eb-11e7-9ee2-09e697948e60.gif)

But the information in the Starcounter debugger is correct :

![image](https://user-images.githubusercontent.com/10708580/29267957-343026ac-80eb-11e7-8778-97758420d299.png)

![incrementationstillworks](https://user-images.githubusercontent.com/10708580/29268028-70fddd04-80eb-11e7-882c-befa2c815172.gif)

**Comment by alshakero** [comment]
It's probably the same issue. Could you add several items then try to reproduce? 

Because there is another issue with last array item, could you reproduce the isssue with 1,2,3 items when you have say 5 items

**Comment by Joltrix** [comment]
I just tried it with 5 items.
If I delete the last one, there is no problems at all!

If I delete something else, then the last button stops working, even if I delete 2 or 3 items. The last button stops working completely until I refresh the page

**Comment by alshakero** [comment]
Thanks a lot. I'll investigate.

**Comment by alshakero** [comment]
@Joltrix is there a git repo I could clone to see this? Don't do any extra effort if not.

**Comment by Joltrix** [comment]
You can recreate the environment like this:
**SignIn** App - Develop Branch
**People** App - event-creations Branch
**Timeline** App - master Branch
**Notes** App - master Branch

Steps:
1. Log in as Admin
2. Create a Person
3. Go to that Persons "Profile" and click SAVE
4. Delete that Person
5. Go to Admin Admins profile, and click on the CREATE button in the Timeline, and create a Note

Now you should have 4 events: Person Creation, Person Deletion, Person Update and Note

**Comment by alshakero** [comment]
Great thanks! Looking at it.

**Comment by alshakero** [comment]
Checked with @Joltrix and closing as done on https://github.com/Palindrom/JSONPatcherProxy/pull/14.
